name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ssh agent
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary

      - name: Add known hosts
        run: ssh-keyscan -H 46.101.53.207 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ./scripts/deploy.sh
